name: CI

on:
  push:
    branches:
      - main
      - workflow-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use Node.js 14

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Build the application
        run: |
          npm run build --prod # Run build without NODE_OPTIONS

      - name: Run tests
        run: |
          npm test # Replace with your actual test command

      - name: Docker build
        run: |
          docker build -t your-image-name . # Adjust the context and image name as needed
